# PROBLEM 2 (mushrooms.py) 

check = False 
while check == False:  
    print(" welcome to the mushroom prgram") 
    print("1. enter the size of your mushroom")
    print("2. sort mushrooms into groups") 
    print("3. quit") 
    option = input (" enter your option") 
    if option = "1": 
     option = input(" enter the size of your mushrrom") 
     if option.isnumeric(): 
        if option = int(option) 
     if option >= 100:
    option = input (" enter your option ") 
    if option == "2": 
         print("goodbye") 
         check = True 
    else:
        print("not a valid option")  
