"""  
Foundations of Computer Science PSET 2 – String Manipulation
Problem 1 (count.py)
Given the string below
Str = “abbabababbabababababbababababababaaaaababbbbbbababababaababababababababbababaabababaabbabababbabababababbababababababaaaaababbbbbbababababaababababababababbababaabababaabbabababbabababababbababababababaaaaababbbbbbababababaababababababababbababaabababaaaaaababbbbbbababababaababbababbabababbababbabababababbababababababaaaaababbbbbbababababaababababababababbababaabababaabbabababbabababababbababbabababababababbababaabababaabbabababbabababababbababababababaaaaababbbbbbababababaabababababababaabababbababababababaaaaababbbbbbababababaababababababababbababaabababaaaaaababbbbbbababababaababbababbabababbababbbbbbababababaababababababababbababaabababaabbabababbabababababbababababababaaaaababbbbbbababababaababababababababbababaabababaaaaaababbbbbbababababaababbababbabababababababaababbababbabababbababbabababababbababababababaaaaababbbbbbababababaababababababababbababaabababaabbabababbabababababbababbabababababababbababaabababaabbabababbabbababababababaaaaababbbbbbababababaababababababababbababaabababaabbabababbabababababbababababababaaaaababbbbbbababababaababababababababbababaabababaaaaaababbbbbbababababaababbababbabababbababbabababababbababababababaaaaababbbbbbababababaababababababababbababaabababaabbabababbabababababbababbabababababababbababaabababaabb



"""